import type { Locale } from "@/lib/i18n";

const OPTION_LABELS: Record<Locale, Record<string, string>> = {
  ja: {},
  en: {
    "コンドーム破損/外れ": "Condom broke or slipped off",
    "膣外射精の失敗": "Withdrawal failed",
    "避妊なし": "No contraception",
    "その他": "Other",
    "肝臓病": "Liver disease",
    "心臓病・腎臓病": "Heart or kidney disease",
    "重い消化器疾患": "Severe gastrointestinal condition",
    "薬や食品のアレルギー": "Drug or food allergy",
    "その他の病気": "Other condition",
    "わからない": "Not sure",
    "特にない": "None",
    "セイヨウオトギリソウ（セントジョーンズワート）": "St. John's Wort",
    "その他のサプリメント": "Other supplements",
    "特に飲んでいない": "Not taking any",
  },
  zh: {
    "コンドーム破損/外れ": "避孕套破裂或脱落",
    "膣外射精の失敗": "体外射精失败",
    "避妊なし": "未采取避孕措施",
    "その他": "其他",
    "肝臓病": "肝脏疾病",
    "心臓病・腎臓病": "心脏病或肾脏病",
    "重い消化器疾患": "严重的消化系统疾病",
    "薬や食品のアレルギー": "药物或食物过敏",
    "その他の病気": "其他疾病",
    "わからない": "不清楚",
    "特にない": "无",
    "セイヨウオトギリソウ（セントジョーンズワート）": "贯叶连翘（圣约翰草）",
    "その他のサプリメント": "其他保健品",
    "特に飲んでいない": "未服用",
  },
  vi: {
    "コンドーム破損/外れ": "Bao cao su bị rách hoặc tuột",
    "膣外射精の失敗": "Xuất tinh ngoài không thành công",
    "避妊なし": "Không dùng biện pháp tránh thai",
    "その他": "Khác",
    "肝臓病": "Bệnh gan",
    "心臓病・腎臓病": "Bệnh tim hoặc bệnh thận",
    "重い消化器疾患": "Bệnh tiêu hóa nặng",
    "薬や食品のアレルギー": "Dị ứng thuốc hoặc thực phẩm",
    "その他の病気": "Bệnh khác",
    "わからない": "Không rõ",
    "特にない": "Không có",
    "セイヨウオトギリソウ（セントジョーンズワート）": "St. John's Wort (cỏ ban Âu)",
    "その他のサプリメント": "Thực phẩm bổ sung khác",
    "特に飲んでいない": "Không sử dụng",
  },
  ko: {
    "コンドーム破損/外れ": "콘돔 파손 또는 이탈",
    "膣外射精の失敗": "질외사정 실패",
    "避妊なし": "피임하지 않음",
    "その他": "기타",
    "肝臓病": "간 질환",
    "心臓病・腎臓病": "심장병 또는 신장병",
    "重い消化器疾患": "중증 소화기 질환",
    "薬や食品のアレルギー": "약물 또는 음식 알레르기",
    "その他の病気": "기타 질환",
    "わからない": "모름",
    "特にない": "해당 없음",
    "セイヨウオトギリソウ（セントジョーンズワート）": "세인트존스워트",
    "その他のサプリメント": "기타 보충제",
    "特に飲んでいない": "복용하지 않음",
  },
};

export function translateAnswerOption(option: string, locale: Locale): string {
  return OPTION_LABELS[locale][option] ?? option;
}
